apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app:  myapp
spec:
  containers:
  - name: nginx
    image: 174047634073.dkr.ecr.ap-southeast-2.amazonaws.com/anbu
    ports:
    - containerPort: 8080

---


kind: Service
apiVersion: v1
metadata:
  name:  mynodeport
spec:
  selector:
    app:  myapp
  type:  NodePort
  ports:
  - name:  httpd
    port:  80
    targetPort:  8080
    protocol: TCP
